--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XanderID/ChatMath
build-by-default: true
branches:
- main
projects:
  ChatMath:
    path: ""
    icon: "assets/icon.png"
    lint: false
...